0.2::hYPOVOLEMIA_TRUE.
0.8::hYPOVOLEMIA_FALSE.
0.05::lVFAILURE_TRUE.
0.95::lVFAILURE_FALSE.
0.05::eRRLOWOUTPUT_TRUE.
0.95::eRRLOWOUTPUT_FALSE.
0.1::eRRCAUTER_TRUE.
0.9::eRRCAUTER_FALSE.
0.1::iNSUFFANESTH_TRUE.
0.9::iNSUFFANESTH_FALSE.
0.01::aNAPHYLAXIS_TRUE.
0.99::aNAPHYLAXIS_FALSE.
0.04::kINKEDTUBE_TRUE.
0.96::kINKEDTUBE_FALSE.
0.05::fIO2_LOW.
0.95::fIO2_NORMAL.
0.01::pULMEMBOLUS_TRUE.
0.99::pULMEMBOLUS_FALSE.
0.92::iNTUBATION_NORMAL.
0.03::iNTUBATION_ESOPHAGEAL.
0.05::iNTUBATION_ONESIDED.
0.1::dISCONNECT_TRUE.
0.9::dISCONNECT_FALSE.
0.05::mINVOLSET_LOW.
0.9::mINVOLSET_NORMAL.
0.05::mINVOLSET_HIGH.
0.08::hYPOVOLEMIA_TRUE :- lVFAILURE_TRUE.
0::hYPOVOLEMIA_TRUE :- hYPOVOLEMIA_FALSE.
0.07::iNTUBATION_NORMAL :- pULMEMBOLUS_TRUE.
0::iNTUBATION_NORMAL :- iNTUBATION_ESOPHAGEAL.
0::iNTUBATION_NORMAL :- iNTUBATION_ONESIDED.
0.09::mINVOLSET_LOW :- iNTUBATION_NORMAL.
0::mINVOLSET_LOW :- mINVOLSET_NORMAL.
0::mINVOLSET_LOW :- mINVOLSET_HIGH.
0.9::hISTORY_TRUE :- lVFAILURE_TRUE.
0.1::hISTORY_FALSE :- lVFAILURE_TRUE.
0.95::cVP_LOW :- lVEDVOLUME_LOW.
0.04::cVP_NORMAL :- lVEDVOLUME_LOW.
0.01::cVP_HIGH :- lVEDVOLUME_LOW.
0.95::pCWP_LOW :- lVEDVOLUME_LOW.
0.04::pCWP_NORMAL :- lVEDVOLUME_LOW.
0.01::pCWP_HIGH :- lVEDVOLUME_LOW.
0.95::lVEDVOLUME_LOW :- hYPOVOLEMIA_TRUE,lVFAILURE_TRUE.
0.04::lVEDVOLUME_NORMAL :- hYPOVOLEMIA_TRUE,lVFAILURE_TRUE.
0.01::lVEDVOLUME_HIGH :- hYPOVOLEMIA_TRUE,lVFAILURE_TRUE.
0.98::sTROKEVOLUME_LOW :- hYPOVOLEMIA_TRUE,lVFAILURE_TRUE.
0.01::sTROKEVOLUME_NORMAL :- hYPOVOLEMIA_TRUE,lVFAILURE_TRUE.
0.01::sTROKEVOLUME_HIGH :- hYPOVOLEMIA_TRUE,lVFAILURE_TRUE.
0.98::hRBP_LOW :- eRRLOWOUTPUT_TRUE,hR_LOW.
0.01::hRBP_NORMAL :- eRRLOWOUTPUT_TRUE,hR_LOW.
0.01::hRBP_HIGH :- eRRLOWOUTPUT_TRUE,hR_LOW.
0.3333333::hREKG_LOW :- eRRCAUTER_TRUE,hR_LOW.
0.3333333::hREKG_NORMAL :- eRRCAUTER_TRUE,hR_LOW.
0.3333333::hREKG_HIGH :- eRRCAUTER_TRUE,hR_LOW.
0.3333333::hRSAT_LOW :- eRRCAUTER_TRUE,hR_LOW.
0.3333333::hRSAT_NORMAL :- eRRCAUTER_TRUE,hR_LOW.
0.3333333::hRSAT_HIGH :- eRRCAUTER_TRUE,hR_LOW.
0.98::tPR_LOW :- aNAPHYLAXIS_TRUE.
0.01::tPR_NORMAL :- aNAPHYLAXIS_TRUE.
0.01::tPR_HIGH :- aNAPHYLAXIS_TRUE.
0.97::eXPCO2_ZERO :- aRTCO2_LOW,vENTLUNG_ZERO.
0.01::eXPCO2_LOW :- aRTCO2_LOW,vENTLUNG_ZERO.
0.01::eXPCO2_NORMAL :- aRTCO2_LOW,vENTLUNG_ZERO.
0.01::eXPCO2_HIGH :- aRTCO2_LOW,vENTLUNG_ZERO.
0.97::mINVOL_ZERO :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::mINVOL_LOW :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::mINVOL_NORMAL :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::mINVOL_HIGH :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
1.0::pVSAT_LOW :- fIO2_LOW,vENTALV_ZERO.
0.0::pVSAT_NORMAL :- fIO2_LOW,vENTALV_ZERO.
0.0::pVSAT_HIGH :- fIO2_LOW,vENTALV_ZERO.
0.98::sAO2_LOW :- pVSAT_LOW,sHUNT_NORMAL.
0.01::sAO2_NORMAL :- pVSAT_LOW,sHUNT_NORMAL.
0.01::sAO2_HIGH :- pVSAT_LOW,sHUNT_NORMAL.
0.01::pAP_LOW :- pULMEMBOLUS_TRUE.
0.19::pAP_NORMAL :- pULMEMBOLUS_TRUE.
0.8::pAP_HIGH :- pULMEMBOLUS_TRUE.
0.1::sHUNT_NORMAL :- iNTUBATION_NORMAL,pULMEMBOLUS_TRUE.
0.9::sHUNT_HIGH :- iNTUBATION_NORMAL,pULMEMBOLUS_TRUE.
0.97::pRESS_ZERO :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.01::pRESS_LOW :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.01::pRESS_NORMAL :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.01::pRESS_HIGH :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.05::vENTMACH_ZERO :- mINVOLSET_LOW.
0.93::vENTMACH_LOW :- mINVOLSET_LOW.
0.01::vENTMACH_NORMAL :- mINVOLSET_LOW.
0.01::vENTMACH_HIGH :- mINVOLSET_LOW.
0.97::vENTTUBE_ZERO :- dISCONNECT_TRUE,vENTMACH_ZERO.
0.01::vENTTUBE_LOW :- dISCONNECT_TRUE,vENTMACH_ZERO.
0.01::vENTTUBE_NORMAL :- dISCONNECT_TRUE,vENTMACH_ZERO.
0.01::vENTTUBE_HIGH :- dISCONNECT_TRUE,vENTMACH_ZERO.
0.97::vENTLUNG_ZERO :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.01::vENTLUNG_LOW :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.01::vENTLUNG_NORMAL :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.01::vENTLUNG_HIGH :- iNTUBATION_NORMAL,kINKEDTUBE_TRUE,vENTTUBE_ZERO.
0.97::vENTALV_ZERO :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::vENTALV_LOW :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::vENTALV_NORMAL :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::vENTALV_HIGH :- iNTUBATION_NORMAL,vENTLUNG_ZERO.
0.01::aRTCO2_LOW :- vENTALV_ZERO.
0.01::aRTCO2_NORMAL :- vENTALV_ZERO.
0.98::aRTCO2_HIGH :- vENTALV_ZERO.
0.01::cATECHOL_NORMAL :- aRTCO2_LOW,iNSUFFANESTH_TRUE,sAO2_LOW,tPR_LOW.
0.99::cATECHOL_HIGH :- aRTCO2_LOW,iNSUFFANESTH_TRUE,sAO2_LOW,tPR_LOW.
0.05::hR_LOW :- cATECHOL_NORMAL.
0.9::hR_NORMAL :- cATECHOL_NORMAL.
0.05::hR_HIGH :- cATECHOL_NORMAL.
0.98::cO_LOW :- hR_LOW,sTROKEVOLUME_LOW.
0.01::cO_NORMAL :- hR_LOW,sTROKEVOLUME_LOW.
0.01::cO_HIGH :- hR_LOW,sTROKEVOLUME_LOW.
0.98::bP_LOW :- cO_LOW,tPR_LOW.
0.01::bP_NORMAL :- cO_LOW,tPR_LOW.
0.01::bP_HIGH :- cO_LOW,tPR_LOW.
0::lVFAILURE_TRUE :- lVFAILURE_FALSE.
0::eRRLOWOUTPUT_TRUE :- eRRLOWOUTPUT_FALSE.
0::eRRCAUTER_TRUE :- eRRCAUTER_FALSE.
0::iNSUFFANESTH_TRUE :- iNSUFFANESTH_FALSE.
0::aNAPHYLAXIS_TRUE :- aNAPHYLAXIS_FALSE.
0::kINKEDTUBE_TRUE :- kINKEDTUBE_FALSE.
0::fIO2_LOW :- fIO2_NORMAL.
0::pULMEMBOLUS_TRUE :- pULMEMBOLUS_FALSE.
0::dISCONNECT_TRUE :- dISCONNECT_FALSE.
query(hISTORY_TRUE).
query(hISTORY_FALSE).
query(cVP_LOW).
query(cVP_NORMAL).
query(cVP_HIGH).
query(pCWP_LOW).
query(pCWP_NORMAL).
query(pCWP_HIGH).
query(lVEDVOLUME_LOW).
query(lVEDVOLUME_NORMAL).
query(lVEDVOLUME_HIGH).
query(sTROKEVOLUME_LOW).
query(sTROKEVOLUME_NORMAL).
query(sTROKEVOLUME_HIGH).
query(hRBP_LOW).
query(hRBP_NORMAL).
query(hRBP_HIGH).
query(hREKG_LOW).
query(hREKG_NORMAL).
query(hREKG_HIGH).
query(hRSAT_LOW).
query(hRSAT_NORMAL).
query(hRSAT_HIGH).
query(tPR_LOW).
query(tPR_NORMAL).
query(tPR_HIGH).
query(eXPCO2_ZERO).
query(eXPCO2_LOW).
query(eXPCO2_NORMAL).
query(eXPCO2_HIGH).
query(mINVOL_ZERO).
query(mINVOL_LOW).
query(mINVOL_NORMAL).
query(mINVOL_HIGH).
query(pVSAT_LOW).
query(pVSAT_NORMAL).
query(pVSAT_HIGH).
query(sAO2_LOW).
query(sAO2_NORMAL).
query(sAO2_HIGH).
query(pAP_LOW).
query(pAP_NORMAL).
query(pAP_HIGH).
query(sHUNT_NORMAL).
query(sHUNT_HIGH).
query(pRESS_ZERO).
query(pRESS_LOW).
query(pRESS_NORMAL).
query(pRESS_HIGH).
query(vENTMACH_ZERO).
query(vENTMACH_LOW).
query(vENTMACH_NORMAL).
query(vENTMACH_HIGH).
query(vENTTUBE_ZERO).
query(vENTTUBE_LOW).
query(vENTTUBE_NORMAL).
query(vENTTUBE_HIGH).
query(vENTLUNG_ZERO).
query(vENTLUNG_LOW).
query(vENTLUNG_NORMAL).
query(vENTLUNG_HIGH).
query(vENTALV_ZERO).
query(vENTALV_LOW).
query(vENTALV_NORMAL).
query(vENTALV_HIGH).
query(aRTCO2_LOW).
query(aRTCO2_NORMAL).
query(aRTCO2_HIGH).
query(cATECHOL_NORMAL).
query(cATECHOL_HIGH).
query(hR_LOW).
query(hR_NORMAL).
query(hR_HIGH).
query(cO_LOW).
query(cO_NORMAL).
query(cO_HIGH).
query(bP_LOW).
query(bP_NORMAL).
query(bP_HIGH).